[package]
name = "rgis-transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.16", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
    "png",
] }
geo-features = { path = "../geo-features" }
geo-projected = { path = "../geo-projected" }
geo = "0.30"
rgis-events = { path = "../rgis-events" }
rgis-primitives = { path = "../rgis-primitives" }
rgis-layers = { path = "../rgis-layers" }
rgis-settings = { path = "../rgis-settings" }
bevy_jobs = { git = "https://github.com/frewsxcv/bevy_jobs" }
geo-geodesy = "4"
num-t = "3"
rgis-crs = { path = "../rgis-crs" }
rgis-geodesy = { path = "../rgis-geodesy" }
