[package]
name = "geo-projected"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
geo = { workspace = true }
geo-features = { path = "../geo-features", version = "0.1.0" }
num-t = { workspace = true }
