[package]
name = "geo-projected"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
geo = { workspace = true }
geo-features = { path = "../geo-features" }
num-t = { workspace = true }
