[package]
name = "time-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy_log = { workspace = true }
web-time = { workspace = true }
