[package]
name = "bevy_egui_window"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]

bevy = { workspace = true }
bevy_egui = { workspace = true }

[lints]
workspace = true
