[package]
name = "rgis-crs"
version.workspace = true
edition = "2021"
publish.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
geodesy = { workspace = true }
rgis-events = { path = "../rgis-events", version = "0.1.0" }
rgis-primitives = { path = "../rgis-primitives", version = "0.1.0" }
rgis-geodesy = { path = "../rgis-geodesy", version = "0.1.0" }
