[package]
name = "rgis-crs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { version = "0.16", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
    "png",
] }
geodesy = "0.13"
rgis-events = { path = "../rgis-events" }
rgis-primitives = { path = "../rgis-primitives" }
rgis-geodesy = { path = "../rgis-geodesy" }
