[package]
name = "geo-bevy"
version = "0.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy_log = "0.9"
bevy_render = "0.9"
bevy-earcutr = "0.7"
geo = "0.23"
