[package]
name = "rgis-geodesy"
version.workspace = true
edition = "2021"

[dependencies]
bevy = { workspace = true }
geodesy = { workspace = true }
async-lock = { workspace = true }
crs-definitions = { workspace = true }
