[package]
name = "rgis-settings"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
rgis-events = { path = "../rgis-events", version = "0.1.0" }
